DROP TABLE country IF EXISTS;
DROP TABLE city IF EXISTS;
DROP SEQUENCE IF EXISTS country_sequence;
DROP SEQUENCE IF EXISTS city_sequence;

DROP TABLE choice IF EXISTS;
DROP TABLE question IF EXISTS;
DROP TABLE quiz IF EXISTS;
DROP SEQUENCE IF EXISTS question_sequence;
DROP SEQUENCE IF EXISTS quiz_sequence;